# This is a basic workflow to help you get started with Actions
name: CI-CloudResumeFrontEnd

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.EMILS_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EMILS_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.EMILS_AWS_DEFAULT_REGION }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - uses: actions/checkout@v2
          
    # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo S3 update run starting!
          
        - name: Deploy
          uses: reggionick/s3-deploy@v1
          with:
            folder: build
            bucket: ${{ secrets.EMILS_S3_BUCKET }}
            dist-id: ${{ secrets.EMILS_CLOUDFRONT_DISTRIBUTION_ID }}

    # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
            echo S3 bucket update run complete!
            echo End of job.
          
